server:
   # 配置默认的 eureka 端口, 那么客户端网元不要进行配置了
   port: 8761
# 定义当前服务名
spring:
   application:
      name: bseureka
      
eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000